// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_profile.proto

package main.proto;

/**
 * Protobuf type {@code Address}
 */
public  final class Address extends
    com.google.protobuf.GeneratedMessageLite<
        Address, Address.Builder> implements
    // @@protoc_insertion_point(message_implements:Address)
    AddressOrBuilder {
  private Address() {
    street_ = "";
    city_ = "";
    country_ = "";
  }
  public static final int STREET_FIELD_NUMBER = 1;
  private java.lang.String street_;
  /**
   * <code>string street = 1;</code>
   * @return The street.
   */
  @java.lang.Override
  public java.lang.String getStreet() {
    return street_;
  }
  /**
   * <code>string street = 1;</code>
   * @return The bytes for street.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStreetBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(street_);
  }
  /**
   * <code>string street = 1;</code>
   * @param value The street to set.
   */
  private void setStreet(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    street_ = value;
  }
  /**
   * <code>string street = 1;</code>
   */
  private void clearStreet() {

    street_ = getDefaultInstance().getStreet();
  }
  /**
   * <code>string street = 1;</code>
   * @param value The bytes for street to set.
   */
  private void setStreetBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    street_ = value.toStringUtf8();

  }

  public static final int CITY_FIELD_NUMBER = 2;
  private java.lang.String city_;
  /**
   * <code>string city = 2;</code>
   * @return The city.
   */
  @java.lang.Override
  public java.lang.String getCity() {
    return city_;
  }
  /**
   * <code>string city = 2;</code>
   * @return The bytes for city.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCityBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(city_);
  }
  /**
   * <code>string city = 2;</code>
   * @param value The city to set.
   */
  private void setCity(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    city_ = value;
  }
  /**
   * <code>string city = 2;</code>
   */
  private void clearCity() {

    city_ = getDefaultInstance().getCity();
  }
  /**
   * <code>string city = 2;</code>
   * @param value The bytes for city to set.
   */
  private void setCityBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    city_ = value.toStringUtf8();

  }

  public static final int COUNTRY_FIELD_NUMBER = 3;
  private java.lang.String country_;
  /**
   * <code>string country = 3;</code>
   * @return The country.
   */
  @java.lang.Override
  public java.lang.String getCountry() {
    return country_;
  }
  /**
   * <code>string country = 3;</code>
   * @return The bytes for country.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCountryBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(country_);
  }
  /**
   * <code>string country = 3;</code>
   * @param value The country to set.
   */
  private void setCountry(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    country_ = value;
  }
  /**
   * <code>string country = 3;</code>
   */
  private void clearCountry() {

    country_ = getDefaultInstance().getCountry();
  }
  /**
   * <code>string country = 3;</code>
   * @param value The bytes for country to set.
   */
  private void setCountryBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    country_ = value.toStringUtf8();

  }

  public static main.proto.Address parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static main.proto.Address parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static main.proto.Address parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static main.proto.Address parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static main.proto.Address parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static main.proto.Address parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static main.proto.Address parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static main.proto.Address parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static main.proto.Address parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static main.proto.Address parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static main.proto.Address parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static main.proto.Address parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(main.proto.Address prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code Address}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        main.proto.Address, Builder> implements
      // @@protoc_insertion_point(builder_implements:Address)
      main.proto.AddressOrBuilder {
    // Construct using main.proto.Address.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string street = 1;</code>
     * @return The street.
     */
    @java.lang.Override
    public java.lang.String getStreet() {
      return instance.getStreet();
    }
    /**
     * <code>string street = 1;</code>
     * @return The bytes for street.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStreetBytes() {
      return instance.getStreetBytes();
    }
    /**
     * <code>string street = 1;</code>
     * @param value The street to set.
     * @return This builder for chaining.
     */
    public Builder setStreet(
        java.lang.String value) {
      copyOnWrite();
      instance.setStreet(value);
      return this;
    }
    /**
     * <code>string street = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStreet() {
      copyOnWrite();
      instance.clearStreet();
      return this;
    }
    /**
     * <code>string street = 1;</code>
     * @param value The bytes for street to set.
     * @return This builder for chaining.
     */
    public Builder setStreetBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setStreetBytes(value);
      return this;
    }

    /**
     * <code>string city = 2;</code>
     * @return The city.
     */
    @java.lang.Override
    public java.lang.String getCity() {
      return instance.getCity();
    }
    /**
     * <code>string city = 2;</code>
     * @return The bytes for city.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCityBytes() {
      return instance.getCityBytes();
    }
    /**
     * <code>string city = 2;</code>
     * @param value The city to set.
     * @return This builder for chaining.
     */
    public Builder setCity(
        java.lang.String value) {
      copyOnWrite();
      instance.setCity(value);
      return this;
    }
    /**
     * <code>string city = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCity() {
      copyOnWrite();
      instance.clearCity();
      return this;
    }
    /**
     * <code>string city = 2;</code>
     * @param value The bytes for city to set.
     * @return This builder for chaining.
     */
    public Builder setCityBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setCityBytes(value);
      return this;
    }

    /**
     * <code>string country = 3;</code>
     * @return The country.
     */
    @java.lang.Override
    public java.lang.String getCountry() {
      return instance.getCountry();
    }
    /**
     * <code>string country = 3;</code>
     * @return The bytes for country.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCountryBytes() {
      return instance.getCountryBytes();
    }
    /**
     * <code>string country = 3;</code>
     * @param value The country to set.
     * @return This builder for chaining.
     */
    public Builder setCountry(
        java.lang.String value) {
      copyOnWrite();
      instance.setCountry(value);
      return this;
    }
    /**
     * <code>string country = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCountry() {
      copyOnWrite();
      instance.clearCountry();
      return this;
    }
    /**
     * <code>string country = 3;</code>
     * @param value The bytes for country to set.
     * @return This builder for chaining.
     */
    public Builder setCountryBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setCountryBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:Address)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new main.proto.Address();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "street_",
            "city_",
            "country_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<main.proto.Address> parser = PARSER;
        if (parser == null) {
          synchronized (main.proto.Address.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<main.proto.Address>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:Address)
  private static final main.proto.Address DEFAULT_INSTANCE;
  static {
    Address defaultInstance = new Address();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Address.class, defaultInstance);
  }

  public static main.proto.Address getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Address> PARSER;

  public static com.google.protobuf.Parser<Address> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

