// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_profile.proto

package main.proto;

public final class UserProfileOuterClass {
  private UserProfileOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
