// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_profile.proto

package main.proto;

public interface UserProfileOrBuilder extends
    // @@protoc_insertion_point(interface_extends:UserProfile)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>.Address address = 3;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>.Address address = 3;</code>
   * @return The address.
   */
  main.proto.Address getAddress();
}
