// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_profile.proto

package main.proto;

/**
 * Protobuf type {@code UserProfile}
 */
public  final class UserProfile extends
    com.google.protobuf.GeneratedMessageLite<
        UserProfile, UserProfile.Builder> implements
    // @@protoc_insertion_point(message_implements:UserProfile)
    UserProfileOrBuilder {
  private UserProfile() {
    name_ = "";
  }
  public static final int NAME_FIELD_NUMBER = 1;
  private java.lang.String name_;
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    return name_;
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(name_);
  }
  /**
   * <code>string name = 1;</code>
   * @param value The name to set.
   */
  private void setName(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    name_ = value;
  }
  /**
   * <code>string name = 1;</code>
   */
  private void clearName() {

    name_ = getDefaultInstance().getName();
  }
  /**
   * <code>string name = 1;</code>
   * @param value The bytes for name to set.
   */
  private void setNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    name_ = value.toStringUtf8();

  }

  public static final int AGE_FIELD_NUMBER = 2;
  private int age_;
  /**
   * <code>int32 age = 2;</code>
   * @return The age.
   */
  @java.lang.Override
  public int getAge() {
    return age_;
  }
  /**
   * <code>int32 age = 2;</code>
   * @param value The age to set.
   */
  private void setAge(int value) {
    
    age_ = value;
  }
  /**
   * <code>int32 age = 2;</code>
   */
  private void clearAge() {

    age_ = 0;
  }

  public static final int ADDRESS_FIELD_NUMBER = 3;
  private main.proto.Address address_;
  /**
   * <code>.Address address = 3;</code>
   */
  @java.lang.Override
  public boolean hasAddress() {
    return address_ != null;
  }
  /**
   * <code>.Address address = 3;</code>
   */
  @java.lang.Override
  public main.proto.Address getAddress() {
    return address_ == null ? main.proto.Address.getDefaultInstance() : address_;
  }
  /**
   * <code>.Address address = 3;</code>
   */
  private void setAddress(main.proto.Address value) {
    value.getClass();
  address_ = value;

    }
  /**
   * <code>.Address address = 3;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeAddress(main.proto.Address value) {
    value.getClass();
  if (address_ != null &&
        address_ != main.proto.Address.getDefaultInstance()) {
      address_ =
        main.proto.Address.newBuilder(address_).mergeFrom(value).buildPartial();
    } else {
      address_ = value;
    }

  }
  /**
   * <code>.Address address = 3;</code>
   */
  private void clearAddress() {  address_ = null;

  }

  public static main.proto.UserProfile parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static main.proto.UserProfile parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static main.proto.UserProfile parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static main.proto.UserProfile parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static main.proto.UserProfile parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static main.proto.UserProfile parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static main.proto.UserProfile parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static main.proto.UserProfile parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static main.proto.UserProfile parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }

  public static main.proto.UserProfile parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static main.proto.UserProfile parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static main.proto.UserProfile parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(main.proto.UserProfile prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code UserProfile}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        main.proto.UserProfile, Builder> implements
      // @@protoc_insertion_point(builder_implements:UserProfile)
      main.proto.UserProfileOrBuilder {
    // Construct using main.proto.UserProfile.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      return instance.getName();
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return instance.getNameBytes();
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      copyOnWrite();
      instance.setName(value);
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      copyOnWrite();
      instance.clearName();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNameBytes(value);
      return this;
    }

    /**
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return instance.getAge();
    }
    /**
     * <code>int32 age = 2;</code>
     * @param value The age to set.
     * @return This builder for chaining.
     */
    public Builder setAge(int value) {
      copyOnWrite();
      instance.setAge(value);
      return this;
    }
    /**
     * <code>int32 age = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAge() {
      copyOnWrite();
      instance.clearAge();
      return this;
    }

    /**
     * <code>.Address address = 3;</code>
     */
    @java.lang.Override
    public boolean hasAddress() {
      return instance.hasAddress();
    }
    /**
     * <code>.Address address = 3;</code>
     */
    @java.lang.Override
    public main.proto.Address getAddress() {
      return instance.getAddress();
    }
    /**
     * <code>.Address address = 3;</code>
     */
    public Builder setAddress(main.proto.Address value) {
      copyOnWrite();
      instance.setAddress(value);
      return this;
      }
    /**
     * <code>.Address address = 3;</code>
     */
    public Builder setAddress(
        main.proto.Address.Builder builderForValue) {
      copyOnWrite();
      instance.setAddress(builderForValue.build());
      return this;
    }
    /**
     * <code>.Address address = 3;</code>
     */
    public Builder mergeAddress(main.proto.Address value) {
      copyOnWrite();
      instance.mergeAddress(value);
      return this;
    }
    /**
     * <code>.Address address = 3;</code>
     */
    public Builder clearAddress() {  copyOnWrite();
      instance.clearAddress();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:UserProfile)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new main.proto.UserProfile();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "name_",
            "age_",
            "address_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0208\u0002\u0004" +
              "\u0003\t";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<main.proto.UserProfile> parser = PARSER;
        if (parser == null) {
          synchronized (main.proto.UserProfile.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<main.proto.UserProfile>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:UserProfile)
  private static final main.proto.UserProfile DEFAULT_INSTANCE;
  static {
    UserProfile defaultInstance = new UserProfile();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      UserProfile.class, defaultInstance);
  }

  public static main.proto.UserProfile getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<UserProfile> PARSER;

  public static com.google.protobuf.Parser<UserProfile> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

